backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '_posts/'
    fields:
      - { name: Title }
