backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'

_components:
  cover: &cover
    label: Covers
    name: covers
    widget: list
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Image, name: image, widget: image}

  about: &about
    label: About
    name: about
    widget: object
    fields:
      - {label: Image, name: image, widget: image}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - label: Paragraphs
        name: paragraphs
        widget: list
        fields:
          - {label: Text, name: text, widget: string}

  reviews: &reviews
    label: Reviews
    name: reviews
    widget: object
    fields:
      - {label: Title, name: title, widget: string}
      - label: List
        name: list
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Name, name: name, widget: string}
          - {label: Text, name: text, widget: string}

  gallery: &gallery
    label: Gallery
    name: gallery
    widget: object
    fields:
      - {label: Title, name: title, widget: string}
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Image, name: url, widget: image}

  videos: &videos
    label: Videos
    name: videos
    widget: object
    fields:
      - {label: Title, name: title, widget: string}
      - label: List
        name: list
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Video URL, name: url, widget: string}

  services: &services
    label: Services
    name: services
    widget: object
    fields:
      - {label: Title, name: title, widget: string}
      - label: List
        name: list
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}

collections:

  # ENGLISH
  - label: "English"
    name: "english"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/en/home.yml"
        fields:
          - <<: *cover
          - <<: *about
            label: About 1
            name: about_1
          - <<: *gallery
            label: Gallery 1
            name: gallery_1
          - <<: *about
            label: About 2
            name: about_2
          - <<: *gallery
            label: Gallery 2
            name: gallery_2
          - <<: *videos

      - label: "Agenda page"
        name: "agenda"
        file: "_data/en/agenda.yml"
        fields:
          - <<: *cover

      - label: "Swing dancing page"
        name: "swing_dancing"
        file: "_data/en/swing-events.yml"
        fields:
          - <<: *cover
          - <<: *about
          - <<: *videos

      - label: "Private events page"
        name: "private_events"
        file: "_data/en/private-events.yml"
        fields:
          - <<: *cover
          - <<: *about
          - <<: *gallery
          - <<: *services
          - <<: *reviews

      - label: "Contact page"
        name: "contact"
        file: "_data/en/contact.yml"
        fields:
          - <<: *cover

  # PORTUGUESE
  - label: "Portuguese"
    name: "portuguese"
    files:
      - label: "Test"
        name: "pt"
        file: "_data/pt/test.yml"
        fields:
          - {label: Title, name: title, widget: string}
