covers:
  - title: Private events
    subtitle: Enjoy With Us
    image: /assets/images/heros/hero_2.jpg
about:
  image: /assets/images/about/about_3.jpg
  title: More
  subtitle: Let's swing!
  paragraphs:
    - text: >-
        Bragging about what we've done (smooth fm, swing festivals, tv awards,
        weddings...) Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Eaque, nisi Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Odit nobis magni eaque velit eum, id rem eveniet dolor possimus
        voluptas.
    - text: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, nisi
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit nobis
        magni eaque velit eum, id rem eveniet dolor possimus voluptas.
gallery:
  title: Gallery
  link: /en/private-events
  images:
    - url: /assets/images/gallery-events/img_1.jpg
    - url: /assets/images/gallery-events/img_2.jpg
    - url: /assets/images/gallery-events/img_3.jpg
    - url: /assets/images/gallery-events/img_4.jpg
    - url: /assets/images/gallery-events/img_5.jpg
    - url: /assets/images/gallery-events/img_6.jpg
    - url: /assets/images/gallery-events/img_7.jpg
    - url: /assets/images/gallery-events/img_8.jpg
services:
  title: Services
  list:
    - title: Dj
      description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, nisi
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit nobis
        magni eaque velit eum, id rem eveniet dolor possimus voluptas.
      image: /assets/images/gallery-events/img_5.jpg
    - title: Duo
      description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, nisi
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit nobis
        magni eaque velit eum, id rem eveniet dolor possimus voluptas.
      image: /assets/images/gallery-events/img_2.jpg
    - title: Trio
      description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, nisi
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit nobis
        magni eaque velit eum, id rem eveniet dolor possimus voluptas.
      image: /assets/images/gallery-events/img_3.jpg
    - title: Full power
      description: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, nisi
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit nobis
        magni eaque velit eum, id rem eveniet dolor possimus voluptas.
      image: /assets/images/gallery-events/img_4.jpg
videos:
  title: Videos
  list:
    - image: /assets/images/video/smooth-what-a-night.jpg
      url: 'https://www.youtube.com/watch?v=U61pDogbbfQ'
    - image: /assets/images/video/sofar.jpg
      url: 'https://www.youtube.com/watch?v=VWyw0MYZBFs'
    - image: /assets/images/video/sugartown.jpg
      url: 'https://www.youtube.com/watch?v=kCCiSLHScAg'
    - image: /assets/images/video/promo.jpg
      url: 'https://www.youtube.com/watch?v=VKw_Ja4HSCs'
reviews:
  title: Reviews
  list:
    - image: /assets/uploads/2019_10_12-boda-sonia-y-bernardo-791-1-.jpg
      name: 'Sónia & Bernardo (ES/PT), Wedding, 2019'
      text: >-
        The performance as a band and as DJ duo was a total success, everyone
        talks about how much they liked the band and how cool it was. We are
        very happy that 24 Robbers were a part of our day and we feel that they
        do their job with passion and love, this absolutely makes the
        difference.
    - image: /assets/uploads/62005570_2400331350254156_691332448658653184_o-3-.jpg
      name: 'Rita Monteiro (PT) / Wedding, 2018'
      text: >-
        The event was a success, it was so energetic and so much fun. The band
        put on a hell-of-a performance! Everybody loved the music, and the
        voltage they put into it. They have the gift of music, of turning spaces
        into joyous places. We are so happy 24 Robbers were part of our wedding.
        Thank you!
    - image: /assets/uploads/banquet_1067.jpg
      name: 'Antti Pitkänen (FI) Wedding, 2020'
      text: >-
        We booked 24 Robbers Swing Band for our wedding in Lisbon, Portugal. The
        communication with the band was smooth and we felt that they were very
        trustworthy from the beginning. They even promised to make a jazz swing
        version of Heroes by David Bowie and also to set up some PA-equipment
        for the venue. We met Kristina, the singer of the band, face-to-face on
        the day of the wedding. She seemed really nice and comforting in the
        middle of our wedding day stress and helped with everything possible. We
        felt like we were in the hands of true professionals. And when the band
        started to play, oh my... They were amazing. I am a musician and it was
        important for me to have a good band, but I was not prepared for this
        quality... From the always on time and tasty walking bass lines, to
        steady trickery of the drummer, to the soothing and at the same time
        wild trumpet fills, to the extremely tasteful guitarist and as a cherry
        on the top, amazingly beautiful singing. I was a bit sad that I couldn't
        focus more on the music and that I had to meet other guests, because
        that was how much I enjoyed them. After the show, all the band members
        seemed really nice and cool people and we felt that they genuinely
        enjoyed being there also. If you like jazz, book this band. If you don't
        like jazz, book them still and maybe they change your heart about it.
        Thank you so much!
    - image: /assets/uploads/img_20180825_165740_455.jpg
      name: 'Claire Mcananey (UK) / Wedding, 2018'
      text: >-
        I'd like to thank 24 Robbers for Saturday - we had such a wonderful
        wedding and all our guests keep saying that the band were just perfect!
        I would definitely recommend them for other couples.
    - image: /assets/uploads/73458826_2510489749238315_7901297458657886208_o.jpg
      text: >-
        The best band in town! They know how to spread positive energy and bring
        everyone into the dance floor. They are all very friendly and lovely.
      name: 'Luana Zerillo (IT) / Baptizing, 2018'
    - text: >-
        We didn’t know the band before, but I have to say that it was a pleasant
        surprise. We didn’t have to worry about anything, since the first
        contact Kristina was very helpful. We chose the songs that we really
        wanted to hear and they played them in the right moments. We are very
        satisfied with their work. Thank you for the marvelous day you’ve helped
        to create.
      name: 'Ricardo Santos (PT) / Wedding, 2019'
      image: /assets/uploads/0319.jpg
    - text: >-
        The band was absolutely incredible. Every single guest spoke to us about
        what a great band we had chosen, they loved their style and everyone had
        a great time.
      name: 'Matthew Calvin (UK) / Wedding, 2019'
      image: /assets/uploads/matt-lena-wedding-photography-portugal-4.jpg
    - text: >-
        The band and dancers were perfect and so wonderful to work with -
        arrived early, stayed late, clear communication, so friendly and of
        course talented!! Thank you very much
      name: 'Ashley MacArthur (CA) / Corporate event, 2019'
      image: /assets/uploads/79294684_550653582333514_2657419166524375040_o.jpg
    - text: >-
        The band were fantastic! Our guests gave great feedback and when we
        returned to the cocktail hour having taken some photos, the band who
        were about to take a break came back on to play some songs for us. Our
        only regret was not being able to enjoy their music for longer. Our
        thanks and appreciation to the band!
      name: 'Nae Timi (UK) / Wedding, 2019'
      image: >-
        /assets/uploads/portugalweddingphotographer_quintadohespanhol_fallwedding_1058.jpg
    - name: 'Alexander Soderholm (SE) / Wedding, 2019'
      text: >-
        We just wanted to send across a huge thank you for the wonderful
        ambiance you created at our wedding! Everyone absolutely loved you and
        the music, it was such a beautiful, seamless transition from the
        ceremony to the cocktails. Thank you for being part of creating the most
        magical day of our lives. On behalf of all our wedding guests, sending
        you a huge thank you and our best wishes for all your future gigs! We
        hope to see you all again soon!
      image: /assets/uploads/67093323_2433901603563797_1216723905213890560_o.jpg
